# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sudoku.ui'
#
# Created: Tue Dec  8 14:32:34 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(483, 648)
        MainWindow.setMinimumSize(QtCore.QSize(483, 648))
        MainWindow.setMaximumSize(QtCore.QSize(483, 648))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 471))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cel_2_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_2_2.sizePolicy().hasHeightForWidth())
        self.cel_2_2.setSizePolicy(sizePolicy)
        self.cel_2_2.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_2_2.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_2_2.setFont(font)
        self.cel_2_2.setMaxLength(1)
        self.cel_2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_2.setPlaceholderText(_fromUtf8(""))
        self.cel_2_2.setObjectName(_fromUtf8("cel_2_2"))
        self.gridLayout.addWidget(self.cel_2_2, 2, 2, 1, 1)
        self.cel_0_6 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_0_6.sizePolicy().hasHeightForWidth())
        self.cel_0_6.setSizePolicy(sizePolicy)
        self.cel_0_6.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_0_6.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_0_6.setFont(font)
        self.cel_0_6.setMaxLength(1)
        self.cel_0_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_6.setPlaceholderText(_fromUtf8(""))
        self.cel_0_6.setObjectName(_fromUtf8("cel_0_6"))
        self.gridLayout.addWidget(self.cel_0_6, 0, 6, 1, 1)
        self.cel_1_6 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_1_6.sizePolicy().hasHeightForWidth())
        self.cel_1_6.setSizePolicy(sizePolicy)
        self.cel_1_6.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_1_6.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_1_6.setFont(font)
        self.cel_1_6.setMaxLength(1)
        self.cel_1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_6.setPlaceholderText(_fromUtf8(""))
        self.cel_1_6.setObjectName(_fromUtf8("cel_1_6"))
        self.gridLayout.addWidget(self.cel_1_6, 1, 6, 1, 1)
        self.cel_2_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_2_0.sizePolicy().hasHeightForWidth())
        self.cel_2_0.setSizePolicy(sizePolicy)
        self.cel_2_0.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_2_0.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_2_0.setFont(font)
        self.cel_2_0.setMaxLength(1)
        self.cel_2_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_0.setPlaceholderText(_fromUtf8(""))
        self.cel_2_0.setObjectName(_fromUtf8("cel_2_0"))
        self.gridLayout.addWidget(self.cel_2_0, 2, 0, 1, 1)
        self.cel_1_8 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_1_8.sizePolicy().hasHeightForWidth())
        self.cel_1_8.setSizePolicy(sizePolicy)
        self.cel_1_8.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_1_8.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_1_8.setFont(font)
        self.cel_1_8.setMaxLength(1)
        self.cel_1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_8.setPlaceholderText(_fromUtf8(""))
        self.cel_1_8.setObjectName(_fromUtf8("cel_1_8"))
        self.gridLayout.addWidget(self.cel_1_8, 1, 8, 1, 1)
        self.cel_1_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_1_0.sizePolicy().hasHeightForWidth())
        self.cel_1_0.setSizePolicy(sizePolicy)
        self.cel_1_0.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_1_0.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_1_0.setFont(font)
        self.cel_1_0.setMaxLength(1)
        self.cel_1_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_0.setPlaceholderText(_fromUtf8(""))
        self.cel_1_0.setObjectName(_fromUtf8("cel_1_0"))
        self.gridLayout.addWidget(self.cel_1_0, 1, 0, 1, 1)
        self.cel_1_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_1_3.sizePolicy().hasHeightForWidth())
        self.cel_1_3.setSizePolicy(sizePolicy)
        self.cel_1_3.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_1_3.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_1_3.setFont(font)
        self.cel_1_3.setMaxLength(1)
        self.cel_1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_3.setPlaceholderText(_fromUtf8(""))
        self.cel_1_3.setObjectName(_fromUtf8("cel_1_3"))
        self.gridLayout.addWidget(self.cel_1_3, 1, 3, 1, 1)
        self.cel_3_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_3_0.sizePolicy().hasHeightForWidth())
        self.cel_3_0.setSizePolicy(sizePolicy)
        self.cel_3_0.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_3_0.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_3_0.setFont(font)
        self.cel_3_0.setMaxLength(1)
        self.cel_3_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_0.setPlaceholderText(_fromUtf8(""))
        self.cel_3_0.setObjectName(_fromUtf8("cel_3_0"))
        self.gridLayout.addWidget(self.cel_3_0, 3, 0, 1, 1)
        self.cel_5_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_5_0.sizePolicy().hasHeightForWidth())
        self.cel_5_0.setSizePolicy(sizePolicy)
        self.cel_5_0.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_5_0.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_5_0.setFont(font)
        self.cel_5_0.setMaxLength(1)
        self.cel_5_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_5_0.setPlaceholderText(_fromUtf8(""))
        self.cel_5_0.setObjectName(_fromUtf8("cel_5_0"))
        self.gridLayout.addWidget(self.cel_5_0, 5, 0, 1, 1)
        self.cel_1_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_1_2.sizePolicy().hasHeightForWidth())
        self.cel_1_2.setSizePolicy(sizePolicy)
        self.cel_1_2.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_1_2.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_1_2.setFont(font)
        self.cel_1_2.setMaxLength(1)
        self.cel_1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_2.setPlaceholderText(_fromUtf8(""))
        self.cel_1_2.setObjectName(_fromUtf8("cel_1_2"))
        self.gridLayout.addWidget(self.cel_1_2, 1, 2, 1, 1)
        self.cel_0_8 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_0_8.sizePolicy().hasHeightForWidth())
        self.cel_0_8.setSizePolicy(sizePolicy)
        self.cel_0_8.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_0_8.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_0_8.setFont(font)
        self.cel_0_8.setMaxLength(1)
        self.cel_0_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_8.setPlaceholderText(_fromUtf8(""))
        self.cel_0_8.setObjectName(_fromUtf8("cel_0_8"))
        self.gridLayout.addWidget(self.cel_0_8, 0, 8, 1, 1)
        self.cel_1_7 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_1_7.sizePolicy().hasHeightForWidth())
        self.cel_1_7.setSizePolicy(sizePolicy)
        self.cel_1_7.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_1_7.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_1_7.setFont(font)
        self.cel_1_7.setMaxLength(1)
        self.cel_1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_7.setPlaceholderText(_fromUtf8(""))
        self.cel_1_7.setObjectName(_fromUtf8("cel_1_7"))
        self.gridLayout.addWidget(self.cel_1_7, 1, 7, 1, 1)
        self.cel_0_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_0_3.sizePolicy().hasHeightForWidth())
        self.cel_0_3.setSizePolicy(sizePolicy)
        self.cel_0_3.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_0_3.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_0_3.setFont(font)
        self.cel_0_3.setMaxLength(1)
        self.cel_0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_3.setPlaceholderText(_fromUtf8(""))
        self.cel_0_3.setObjectName(_fromUtf8("cel_0_3"))
        self.gridLayout.addWidget(self.cel_0_3, 0, 3, 1, 1)
        self.cel_7_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_7_0.sizePolicy().hasHeightForWidth())
        self.cel_7_0.setSizePolicy(sizePolicy)
        self.cel_7_0.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_7_0.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_7_0.setFont(font)
        self.cel_7_0.setMaxLength(1)
        self.cel_7_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_7_0.setPlaceholderText(_fromUtf8(""))
        self.cel_7_0.setObjectName(_fromUtf8("cel_7_0"))
        self.gridLayout.addWidget(self.cel_7_0, 7, 0, 1, 1)
        self.cel_4_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_4_0.sizePolicy().hasHeightForWidth())
        self.cel_4_0.setSizePolicy(sizePolicy)
        self.cel_4_0.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_4_0.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_4_0.setFont(font)
        self.cel_4_0.setMaxLength(1)
        self.cel_4_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_4_0.setPlaceholderText(_fromUtf8(""))
        self.cel_4_0.setObjectName(_fromUtf8("cel_4_0"))
        self.gridLayout.addWidget(self.cel_4_0, 4, 0, 1, 1)
        self.cel_0_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_0_4.sizePolicy().hasHeightForWidth())
        self.cel_0_4.setSizePolicy(sizePolicy)
        self.cel_0_4.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_0_4.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_0_4.setFont(font)
        self.cel_0_4.setMaxLength(1)
        self.cel_0_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_4.setPlaceholderText(_fromUtf8(""))
        self.cel_0_4.setObjectName(_fromUtf8("cel_0_4"))
        self.gridLayout.addWidget(self.cel_0_4, 0, 4, 1, 1)
        self.cel_0_5 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_0_5.sizePolicy().hasHeightForWidth())
        self.cel_0_5.setSizePolicy(sizePolicy)
        self.cel_0_5.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_0_5.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_0_5.setFont(font)
        self.cel_0_5.setMaxLength(1)
        self.cel_0_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_5.setPlaceholderText(_fromUtf8(""))
        self.cel_0_5.setObjectName(_fromUtf8("cel_0_5"))
        self.gridLayout.addWidget(self.cel_0_5, 0, 5, 1, 1)
        self.cel_6_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_6_0.sizePolicy().hasHeightForWidth())
        self.cel_6_0.setSizePolicy(sizePolicy)
        self.cel_6_0.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_6_0.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_6_0.setFont(font)
        self.cel_6_0.setMaxLength(1)
        self.cel_6_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_6_0.setPlaceholderText(_fromUtf8(""))
        self.cel_6_0.setObjectName(_fromUtf8("cel_6_0"))
        self.gridLayout.addWidget(self.cel_6_0, 6, 0, 1, 1)
        self.cel_1_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_1_4.sizePolicy().hasHeightForWidth())
        self.cel_1_4.setSizePolicy(sizePolicy)
        self.cel_1_4.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_1_4.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_1_4.setFont(font)
        self.cel_1_4.setMaxLength(1)
        self.cel_1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_4.setPlaceholderText(_fromUtf8(""))
        self.cel_1_4.setObjectName(_fromUtf8("cel_1_4"))
        self.gridLayout.addWidget(self.cel_1_4, 1, 4, 1, 1)
        self.cel_1_5 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_1_5.sizePolicy().hasHeightForWidth())
        self.cel_1_5.setSizePolicy(sizePolicy)
        self.cel_1_5.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_1_5.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_1_5.setFont(font)
        self.cel_1_5.setMaxLength(1)
        self.cel_1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_5.setPlaceholderText(_fromUtf8(""))
        self.cel_1_5.setObjectName(_fromUtf8("cel_1_5"))
        self.gridLayout.addWidget(self.cel_1_5, 1, 5, 1, 1)
        self.cel_2_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_2_1.sizePolicy().hasHeightForWidth())
        self.cel_2_1.setSizePolicy(sizePolicy)
        self.cel_2_1.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_2_1.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_2_1.setFont(font)
        self.cel_2_1.setMaxLength(1)
        self.cel_2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_1.setPlaceholderText(_fromUtf8(""))
        self.cel_2_1.setObjectName(_fromUtf8("cel_2_1"))
        self.gridLayout.addWidget(self.cel_2_1, 2, 1, 1, 1)
        self.cel_1_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_1_1.sizePolicy().hasHeightForWidth())
        self.cel_1_1.setSizePolicy(sizePolicy)
        self.cel_1_1.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_1_1.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_1_1.setFont(font)
        self.cel_1_1.setMaxLength(1)
        self.cel_1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_1.setPlaceholderText(_fromUtf8(""))
        self.cel_1_1.setObjectName(_fromUtf8("cel_1_1"))
        self.gridLayout.addWidget(self.cel_1_1, 1, 1, 1, 1)
        self.cel_8_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_8_0.sizePolicy().hasHeightForWidth())
        self.cel_8_0.setSizePolicy(sizePolicy)
        self.cel_8_0.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_8_0.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_8_0.setFont(font)
        self.cel_8_0.setMaxLength(1)
        self.cel_8_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_8_0.setPlaceholderText(_fromUtf8(""))
        self.cel_8_0.setObjectName(_fromUtf8("cel_8_0"))
        self.gridLayout.addWidget(self.cel_8_0, 8, 0, 1, 1)
        self.cel_0_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_0_0.sizePolicy().hasHeightForWidth())
        self.cel_0_0.setSizePolicy(sizePolicy)
        self.cel_0_0.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_0_0.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_0_0.setFont(font)
        self.cel_0_0.setMaxLength(1)
        self.cel_0_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_0.setPlaceholderText(_fromUtf8(""))
        self.cel_0_0.setObjectName(_fromUtf8("cel_0_0"))
        self.gridLayout.addWidget(self.cel_0_0, 0, 0, 1, 1)
        self.cel_0_7 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_0_7.sizePolicy().hasHeightForWidth())
        self.cel_0_7.setSizePolicy(sizePolicy)
        self.cel_0_7.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_0_7.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_0_7.setFont(font)
        self.cel_0_7.setMaxLength(1)
        self.cel_0_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_7.setPlaceholderText(_fromUtf8(""))
        self.cel_0_7.setObjectName(_fromUtf8("cel_0_7"))
        self.gridLayout.addWidget(self.cel_0_7, 0, 7, 1, 1)
        self.cel_0_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_0_1.sizePolicy().hasHeightForWidth())
        self.cel_0_1.setSizePolicy(sizePolicy)
        self.cel_0_1.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_0_1.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_0_1.setFont(font)
        self.cel_0_1.setMaxLength(1)
        self.cel_0_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_1.setPlaceholderText(_fromUtf8(""))
        self.cel_0_1.setObjectName(_fromUtf8("cel_0_1"))
        self.gridLayout.addWidget(self.cel_0_1, 0, 1, 1, 1)
        self.cel_0_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_0_2.sizePolicy().hasHeightForWidth())
        self.cel_0_2.setSizePolicy(sizePolicy)
        self.cel_0_2.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_0_2.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_0_2.setFont(font)
        self.cel_0_2.setMaxLength(1)
        self.cel_0_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_2.setPlaceholderText(_fromUtf8(""))
        self.cel_0_2.setObjectName(_fromUtf8("cel_0_2"))
        self.gridLayout.addWidget(self.cel_0_2, 0, 2, 1, 1)
        self.cel_2_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_2_3.sizePolicy().hasHeightForWidth())
        self.cel_2_3.setSizePolicy(sizePolicy)
        self.cel_2_3.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_2_3.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_2_3.setFont(font)
        self.cel_2_3.setMaxLength(1)
        self.cel_2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_3.setPlaceholderText(_fromUtf8(""))
        self.cel_2_3.setObjectName(_fromUtf8("cel_2_3"))
        self.gridLayout.addWidget(self.cel_2_3, 2, 3, 1, 1)
        self.cel_2_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_2_4.sizePolicy().hasHeightForWidth())
        self.cel_2_4.setSizePolicy(sizePolicy)
        self.cel_2_4.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_2_4.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_2_4.setFont(font)
        self.cel_2_4.setMaxLength(1)
        self.cel_2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_4.setPlaceholderText(_fromUtf8(""))
        self.cel_2_4.setObjectName(_fromUtf8("cel_2_4"))
        self.gridLayout.addWidget(self.cel_2_4, 2, 4, 1, 1)
        self.cel_2_5 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_2_5.sizePolicy().hasHeightForWidth())
        self.cel_2_5.setSizePolicy(sizePolicy)
        self.cel_2_5.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_2_5.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_2_5.setFont(font)
        self.cel_2_5.setMaxLength(1)
        self.cel_2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_5.setPlaceholderText(_fromUtf8(""))
        self.cel_2_5.setObjectName(_fromUtf8("cel_2_5"))
        self.gridLayout.addWidget(self.cel_2_5, 2, 5, 1, 1)
        self.cel_2_6 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_2_6.sizePolicy().hasHeightForWidth())
        self.cel_2_6.setSizePolicy(sizePolicy)
        self.cel_2_6.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_2_6.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_2_6.setFont(font)
        self.cel_2_6.setMaxLength(1)
        self.cel_2_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_6.setPlaceholderText(_fromUtf8(""))
        self.cel_2_6.setObjectName(_fromUtf8("cel_2_6"))
        self.gridLayout.addWidget(self.cel_2_6, 2, 6, 1, 1)
        self.cel_2_7 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_2_7.sizePolicy().hasHeightForWidth())
        self.cel_2_7.setSizePolicy(sizePolicy)
        self.cel_2_7.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_2_7.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_2_7.setFont(font)
        self.cel_2_7.setMaxLength(1)
        self.cel_2_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_7.setPlaceholderText(_fromUtf8(""))
        self.cel_2_7.setObjectName(_fromUtf8("cel_2_7"))
        self.gridLayout.addWidget(self.cel_2_7, 2, 7, 1, 1)
        self.cel_2_8 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_2_8.sizePolicy().hasHeightForWidth())
        self.cel_2_8.setSizePolicy(sizePolicy)
        self.cel_2_8.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_2_8.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_2_8.setFont(font)
        self.cel_2_8.setMaxLength(1)
        self.cel_2_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_8.setPlaceholderText(_fromUtf8(""))
        self.cel_2_8.setObjectName(_fromUtf8("cel_2_8"))
        self.gridLayout.addWidget(self.cel_2_8, 2, 8, 1, 1)
        self.cel_3_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_3_1.sizePolicy().hasHeightForWidth())
        self.cel_3_1.setSizePolicy(sizePolicy)
        self.cel_3_1.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_3_1.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_3_1.setFont(font)
        self.cel_3_1.setMaxLength(1)
        self.cel_3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_1.setPlaceholderText(_fromUtf8(""))
        self.cel_3_1.setObjectName(_fromUtf8("cel_3_1"))
        self.gridLayout.addWidget(self.cel_3_1, 3, 1, 1, 1)
        self.cel_3_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_3_2.sizePolicy().hasHeightForWidth())
        self.cel_3_2.setSizePolicy(sizePolicy)
        self.cel_3_2.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_3_2.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_3_2.setFont(font)
        self.cel_3_2.setMaxLength(1)
        self.cel_3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_2.setPlaceholderText(_fromUtf8(""))
        self.cel_3_2.setObjectName(_fromUtf8("cel_3_2"))
        self.gridLayout.addWidget(self.cel_3_2, 3, 2, 1, 1)
        self.cel_3_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_3_3.sizePolicy().hasHeightForWidth())
        self.cel_3_3.setSizePolicy(sizePolicy)
        self.cel_3_3.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_3_3.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_3_3.setFont(font)
        self.cel_3_3.setMaxLength(1)
        self.cel_3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_3.setPlaceholderText(_fromUtf8(""))
        self.cel_3_3.setObjectName(_fromUtf8("cel_3_3"))
        self.gridLayout.addWidget(self.cel_3_3, 3, 3, 1, 1)
        self.cel_3_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_3_4.sizePolicy().hasHeightForWidth())
        self.cel_3_4.setSizePolicy(sizePolicy)
        self.cel_3_4.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_3_4.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_3_4.setFont(font)
        self.cel_3_4.setMaxLength(1)
        self.cel_3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_4.setPlaceholderText(_fromUtf8(""))
        self.cel_3_4.setObjectName(_fromUtf8("cel_3_4"))
        self.gridLayout.addWidget(self.cel_3_4, 3, 4, 1, 1)
        self.cel_3_5 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_3_5.sizePolicy().hasHeightForWidth())
        self.cel_3_5.setSizePolicy(sizePolicy)
        self.cel_3_5.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_3_5.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_3_5.setFont(font)
        self.cel_3_5.setMaxLength(1)
        self.cel_3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_5.setPlaceholderText(_fromUtf8(""))
        self.cel_3_5.setObjectName(_fromUtf8("cel_3_5"))
        self.gridLayout.addWidget(self.cel_3_5, 3, 5, 1, 1)
        self.cel_3_6 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_3_6.sizePolicy().hasHeightForWidth())
        self.cel_3_6.setSizePolicy(sizePolicy)
        self.cel_3_6.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_3_6.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_3_6.setFont(font)
        self.cel_3_6.setMaxLength(1)
        self.cel_3_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_6.setPlaceholderText(_fromUtf8(""))
        self.cel_3_6.setObjectName(_fromUtf8("cel_3_6"))
        self.gridLayout.addWidget(self.cel_3_6, 3, 6, 1, 1)
        self.cel_3_7 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_3_7.sizePolicy().hasHeightForWidth())
        self.cel_3_7.setSizePolicy(sizePolicy)
        self.cel_3_7.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_3_7.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_3_7.setFont(font)
        self.cel_3_7.setMaxLength(1)
        self.cel_3_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_7.setPlaceholderText(_fromUtf8(""))
        self.cel_3_7.setObjectName(_fromUtf8("cel_3_7"))
        self.gridLayout.addWidget(self.cel_3_7, 3, 7, 1, 1)
        self.cel_3_8 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_3_8.sizePolicy().hasHeightForWidth())
        self.cel_3_8.setSizePolicy(sizePolicy)
        self.cel_3_8.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_3_8.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_3_8.setFont(font)
        self.cel_3_8.setMaxLength(1)
        self.cel_3_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_8.setPlaceholderText(_fromUtf8(""))
        self.cel_3_8.setObjectName(_fromUtf8("cel_3_8"))
        self.gridLayout.addWidget(self.cel_3_8, 3, 8, 1, 1)
        self.cel_4_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_4_1.sizePolicy().hasHeightForWidth())
        self.cel_4_1.setSizePolicy(sizePolicy)
        self.cel_4_1.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_4_1.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_4_1.setFont(font)
        self.cel_4_1.setMaxLength(1)
        self.cel_4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_4_1.setPlaceholderText(_fromUtf8(""))
        self.cel_4_1.setObjectName(_fromUtf8("cel_4_1"))
        self.gridLayout.addWidget(self.cel_4_1, 4, 1, 1, 1)
        self.cel_4_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_4_2.sizePolicy().hasHeightForWidth())
        self.cel_4_2.setSizePolicy(sizePolicy)
        self.cel_4_2.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_4_2.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_4_2.setFont(font)
        self.cel_4_2.setMaxLength(1)
        self.cel_4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_4_2.setPlaceholderText(_fromUtf8(""))
        self.cel_4_2.setObjectName(_fromUtf8("cel_4_2"))
        self.gridLayout.addWidget(self.cel_4_2, 4, 2, 1, 1)
        self.cel_4_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_4_3.sizePolicy().hasHeightForWidth())
        self.cel_4_3.setSizePolicy(sizePolicy)
        self.cel_4_3.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_4_3.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_4_3.setFont(font)
        self.cel_4_3.setMaxLength(1)
        self.cel_4_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_4_3.setPlaceholderText(_fromUtf8(""))
        self.cel_4_3.setObjectName(_fromUtf8("cel_4_3"))
        self.gridLayout.addWidget(self.cel_4_3, 4, 3, 1, 1)
        self.cel_4_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_4_4.sizePolicy().hasHeightForWidth())
        self.cel_4_4.setSizePolicy(sizePolicy)
        self.cel_4_4.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_4_4.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_4_4.setFont(font)
        self.cel_4_4.setMaxLength(1)
        self.cel_4_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_4_4.setPlaceholderText(_fromUtf8(""))
        self.cel_4_4.setObjectName(_fromUtf8("cel_4_4"))
        self.gridLayout.addWidget(self.cel_4_4, 4, 4, 1, 1)
        self.cel_4_5 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_4_5.sizePolicy().hasHeightForWidth())
        self.cel_4_5.setSizePolicy(sizePolicy)
        self.cel_4_5.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_4_5.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_4_5.setFont(font)
        self.cel_4_5.setMaxLength(1)
        self.cel_4_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_4_5.setPlaceholderText(_fromUtf8(""))
        self.cel_4_5.setObjectName(_fromUtf8("cel_4_5"))
        self.gridLayout.addWidget(self.cel_4_5, 4, 5, 1, 1)
        self.cel_4_6 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_4_6.sizePolicy().hasHeightForWidth())
        self.cel_4_6.setSizePolicy(sizePolicy)
        self.cel_4_6.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_4_6.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_4_6.setFont(font)
        self.cel_4_6.setMaxLength(1)
        self.cel_4_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_4_6.setPlaceholderText(_fromUtf8(""))
        self.cel_4_6.setObjectName(_fromUtf8("cel_4_6"))
        self.gridLayout.addWidget(self.cel_4_6, 4, 6, 1, 1)
        self.cel_4_7 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_4_7.sizePolicy().hasHeightForWidth())
        self.cel_4_7.setSizePolicy(sizePolicy)
        self.cel_4_7.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_4_7.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_4_7.setFont(font)
        self.cel_4_7.setMaxLength(1)
        self.cel_4_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_4_7.setPlaceholderText(_fromUtf8(""))
        self.cel_4_7.setObjectName(_fromUtf8("cel_4_7"))
        self.gridLayout.addWidget(self.cel_4_7, 4, 7, 1, 1)
        self.cel_4_8 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_4_8.sizePolicy().hasHeightForWidth())
        self.cel_4_8.setSizePolicy(sizePolicy)
        self.cel_4_8.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_4_8.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_4_8.setFont(font)
        self.cel_4_8.setMaxLength(1)
        self.cel_4_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_4_8.setPlaceholderText(_fromUtf8(""))
        self.cel_4_8.setObjectName(_fromUtf8("cel_4_8"))
        self.gridLayout.addWidget(self.cel_4_8, 4, 8, 1, 1)
        self.cel_5_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_5_1.sizePolicy().hasHeightForWidth())
        self.cel_5_1.setSizePolicy(sizePolicy)
        self.cel_5_1.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_5_1.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_5_1.setFont(font)
        self.cel_5_1.setMaxLength(1)
        self.cel_5_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_5_1.setPlaceholderText(_fromUtf8(""))
        self.cel_5_1.setObjectName(_fromUtf8("cel_5_1"))
        self.gridLayout.addWidget(self.cel_5_1, 5, 1, 1, 1)
        self.cel_5_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_5_2.sizePolicy().hasHeightForWidth())
        self.cel_5_2.setSizePolicy(sizePolicy)
        self.cel_5_2.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_5_2.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_5_2.setFont(font)
        self.cel_5_2.setMaxLength(1)
        self.cel_5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_5_2.setPlaceholderText(_fromUtf8(""))
        self.cel_5_2.setObjectName(_fromUtf8("cel_5_2"))
        self.gridLayout.addWidget(self.cel_5_2, 5, 2, 1, 1)
        self.cel_5_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_5_3.sizePolicy().hasHeightForWidth())
        self.cel_5_3.setSizePolicy(sizePolicy)
        self.cel_5_3.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_5_3.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_5_3.setFont(font)
        self.cel_5_3.setMaxLength(1)
        self.cel_5_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_5_3.setPlaceholderText(_fromUtf8(""))
        self.cel_5_3.setObjectName(_fromUtf8("cel_5_3"))
        self.gridLayout.addWidget(self.cel_5_3, 5, 3, 1, 1)
        self.cel_5_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_5_4.sizePolicy().hasHeightForWidth())
        self.cel_5_4.setSizePolicy(sizePolicy)
        self.cel_5_4.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_5_4.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_5_4.setFont(font)
        self.cel_5_4.setMaxLength(1)
        self.cel_5_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_5_4.setPlaceholderText(_fromUtf8(""))
        self.cel_5_4.setObjectName(_fromUtf8("cel_5_4"))
        self.gridLayout.addWidget(self.cel_5_4, 5, 4, 1, 1)
        self.cel_5_5 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_5_5.sizePolicy().hasHeightForWidth())
        self.cel_5_5.setSizePolicy(sizePolicy)
        self.cel_5_5.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_5_5.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_5_5.setFont(font)
        self.cel_5_5.setMaxLength(1)
        self.cel_5_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_5_5.setPlaceholderText(_fromUtf8(""))
        self.cel_5_5.setObjectName(_fromUtf8("cel_5_5"))
        self.gridLayout.addWidget(self.cel_5_5, 5, 5, 1, 1)
        self.cel_5_6 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_5_6.sizePolicy().hasHeightForWidth())
        self.cel_5_6.setSizePolicy(sizePolicy)
        self.cel_5_6.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_5_6.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_5_6.setFont(font)
        self.cel_5_6.setMaxLength(1)
        self.cel_5_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_5_6.setPlaceholderText(_fromUtf8(""))
        self.cel_5_6.setObjectName(_fromUtf8("cel_5_6"))
        self.gridLayout.addWidget(self.cel_5_6, 5, 6, 1, 1)
        self.cel_5_7 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_5_7.sizePolicy().hasHeightForWidth())
        self.cel_5_7.setSizePolicy(sizePolicy)
        self.cel_5_7.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_5_7.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_5_7.setFont(font)
        self.cel_5_7.setMaxLength(1)
        self.cel_5_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_5_7.setPlaceholderText(_fromUtf8(""))
        self.cel_5_7.setObjectName(_fromUtf8("cel_5_7"))
        self.gridLayout.addWidget(self.cel_5_7, 5, 7, 1, 1)
        self.cel_5_8 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_5_8.sizePolicy().hasHeightForWidth())
        self.cel_5_8.setSizePolicy(sizePolicy)
        self.cel_5_8.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_5_8.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_5_8.setFont(font)
        self.cel_5_8.setMaxLength(1)
        self.cel_5_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_5_8.setPlaceholderText(_fromUtf8(""))
        self.cel_5_8.setObjectName(_fromUtf8("cel_5_8"))
        self.gridLayout.addWidget(self.cel_5_8, 5, 8, 1, 1)
        self.cel_6_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_6_1.sizePolicy().hasHeightForWidth())
        self.cel_6_1.setSizePolicy(sizePolicy)
        self.cel_6_1.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_6_1.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_6_1.setFont(font)
        self.cel_6_1.setMaxLength(1)
        self.cel_6_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_6_1.setPlaceholderText(_fromUtf8(""))
        self.cel_6_1.setObjectName(_fromUtf8("cel_6_1"))
        self.gridLayout.addWidget(self.cel_6_1, 6, 1, 1, 1)
        self.cel_6_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_6_2.sizePolicy().hasHeightForWidth())
        self.cel_6_2.setSizePolicy(sizePolicy)
        self.cel_6_2.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_6_2.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_6_2.setFont(font)
        self.cel_6_2.setMaxLength(1)
        self.cel_6_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_6_2.setPlaceholderText(_fromUtf8(""))
        self.cel_6_2.setObjectName(_fromUtf8("cel_6_2"))
        self.gridLayout.addWidget(self.cel_6_2, 6, 2, 1, 1)
        self.cel_6_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_6_3.sizePolicy().hasHeightForWidth())
        self.cel_6_3.setSizePolicy(sizePolicy)
        self.cel_6_3.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_6_3.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_6_3.setFont(font)
        self.cel_6_3.setMaxLength(1)
        self.cel_6_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_6_3.setPlaceholderText(_fromUtf8(""))
        self.cel_6_3.setObjectName(_fromUtf8("cel_6_3"))
        self.gridLayout.addWidget(self.cel_6_3, 6, 3, 1, 1)
        self.cel_6_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_6_4.sizePolicy().hasHeightForWidth())
        self.cel_6_4.setSizePolicy(sizePolicy)
        self.cel_6_4.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_6_4.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_6_4.setFont(font)
        self.cel_6_4.setMaxLength(1)
        self.cel_6_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_6_4.setPlaceholderText(_fromUtf8(""))
        self.cel_6_4.setObjectName(_fromUtf8("cel_6_4"))
        self.gridLayout.addWidget(self.cel_6_4, 6, 4, 1, 1)
        self.cel_6_5 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_6_5.sizePolicy().hasHeightForWidth())
        self.cel_6_5.setSizePolicy(sizePolicy)
        self.cel_6_5.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_6_5.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_6_5.setFont(font)
        self.cel_6_5.setMaxLength(1)
        self.cel_6_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_6_5.setPlaceholderText(_fromUtf8(""))
        self.cel_6_5.setObjectName(_fromUtf8("cel_6_5"))
        self.gridLayout.addWidget(self.cel_6_5, 6, 5, 1, 1)
        self.cel_6_6 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_6_6.sizePolicy().hasHeightForWidth())
        self.cel_6_6.setSizePolicy(sizePolicy)
        self.cel_6_6.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_6_6.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_6_6.setFont(font)
        self.cel_6_6.setMaxLength(1)
        self.cel_6_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_6_6.setPlaceholderText(_fromUtf8(""))
        self.cel_6_6.setObjectName(_fromUtf8("cel_6_6"))
        self.gridLayout.addWidget(self.cel_6_6, 6, 6, 1, 1)
        self.cel_6_7 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_6_7.sizePolicy().hasHeightForWidth())
        self.cel_6_7.setSizePolicy(sizePolicy)
        self.cel_6_7.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_6_7.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_6_7.setFont(font)
        self.cel_6_7.setMaxLength(1)
        self.cel_6_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_6_7.setPlaceholderText(_fromUtf8(""))
        self.cel_6_7.setObjectName(_fromUtf8("cel_6_7"))
        self.gridLayout.addWidget(self.cel_6_7, 6, 7, 1, 1)
        self.cel_6_8 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_6_8.sizePolicy().hasHeightForWidth())
        self.cel_6_8.setSizePolicy(sizePolicy)
        self.cel_6_8.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_6_8.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_6_8.setFont(font)
        self.cel_6_8.setMaxLength(1)
        self.cel_6_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_6_8.setPlaceholderText(_fromUtf8(""))
        self.cel_6_8.setObjectName(_fromUtf8("cel_6_8"))
        self.gridLayout.addWidget(self.cel_6_8, 6, 8, 1, 1)
        self.cel_7_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_7_1.sizePolicy().hasHeightForWidth())
        self.cel_7_1.setSizePolicy(sizePolicy)
        self.cel_7_1.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_7_1.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_7_1.setFont(font)
        self.cel_7_1.setMaxLength(1)
        self.cel_7_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_7_1.setPlaceholderText(_fromUtf8(""))
        self.cel_7_1.setObjectName(_fromUtf8("cel_7_1"))
        self.gridLayout.addWidget(self.cel_7_1, 7, 1, 1, 1)
        self.cel_7_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_7_2.sizePolicy().hasHeightForWidth())
        self.cel_7_2.setSizePolicy(sizePolicy)
        self.cel_7_2.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_7_2.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_7_2.setFont(font)
        self.cel_7_2.setMaxLength(1)
        self.cel_7_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_7_2.setPlaceholderText(_fromUtf8(""))
        self.cel_7_2.setObjectName(_fromUtf8("cel_7_2"))
        self.gridLayout.addWidget(self.cel_7_2, 7, 2, 1, 1)
        self.cel_7_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_7_3.sizePolicy().hasHeightForWidth())
        self.cel_7_3.setSizePolicy(sizePolicy)
        self.cel_7_3.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_7_3.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_7_3.setFont(font)
        self.cel_7_3.setMaxLength(1)
        self.cel_7_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_7_3.setPlaceholderText(_fromUtf8(""))
        self.cel_7_3.setObjectName(_fromUtf8("cel_7_3"))
        self.gridLayout.addWidget(self.cel_7_3, 7, 3, 1, 1)
        self.cel_7_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_7_4.sizePolicy().hasHeightForWidth())
        self.cel_7_4.setSizePolicy(sizePolicy)
        self.cel_7_4.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_7_4.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_7_4.setFont(font)
        self.cel_7_4.setMaxLength(1)
        self.cel_7_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_7_4.setPlaceholderText(_fromUtf8(""))
        self.cel_7_4.setObjectName(_fromUtf8("cel_7_4"))
        self.gridLayout.addWidget(self.cel_7_4, 7, 4, 1, 1)
        self.cel_7_5 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_7_5.sizePolicy().hasHeightForWidth())
        self.cel_7_5.setSizePolicy(sizePolicy)
        self.cel_7_5.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_7_5.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_7_5.setFont(font)
        self.cel_7_5.setMaxLength(1)
        self.cel_7_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_7_5.setPlaceholderText(_fromUtf8(""))
        self.cel_7_5.setObjectName(_fromUtf8("cel_7_5"))
        self.gridLayout.addWidget(self.cel_7_5, 7, 5, 1, 1)
        self.cel_7_6 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_7_6.sizePolicy().hasHeightForWidth())
        self.cel_7_6.setSizePolicy(sizePolicy)
        self.cel_7_6.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_7_6.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_7_6.setFont(font)
        self.cel_7_6.setMaxLength(1)
        self.cel_7_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_7_6.setPlaceholderText(_fromUtf8(""))
        self.cel_7_6.setObjectName(_fromUtf8("cel_7_6"))
        self.gridLayout.addWidget(self.cel_7_6, 7, 6, 1, 1)
        self.cel_7_7 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_7_7.sizePolicy().hasHeightForWidth())
        self.cel_7_7.setSizePolicy(sizePolicy)
        self.cel_7_7.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_7_7.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_7_7.setFont(font)
        self.cel_7_7.setMaxLength(1)
        self.cel_7_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_7_7.setPlaceholderText(_fromUtf8(""))
        self.cel_7_7.setObjectName(_fromUtf8("cel_7_7"))
        self.gridLayout.addWidget(self.cel_7_7, 7, 7, 1, 1)
        self.cel_7_8 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_7_8.sizePolicy().hasHeightForWidth())
        self.cel_7_8.setSizePolicy(sizePolicy)
        self.cel_7_8.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_7_8.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_7_8.setFont(font)
        self.cel_7_8.setMaxLength(1)
        self.cel_7_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_7_8.setPlaceholderText(_fromUtf8(""))
        self.cel_7_8.setObjectName(_fromUtf8("cel_7_8"))
        self.gridLayout.addWidget(self.cel_7_8, 7, 8, 1, 1)
        self.cel_8_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_8_1.sizePolicy().hasHeightForWidth())
        self.cel_8_1.setSizePolicy(sizePolicy)
        self.cel_8_1.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_8_1.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_8_1.setFont(font)
        self.cel_8_1.setMaxLength(1)
        self.cel_8_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_8_1.setPlaceholderText(_fromUtf8(""))
        self.cel_8_1.setObjectName(_fromUtf8("cel_8_1"))
        self.gridLayout.addWidget(self.cel_8_1, 8, 1, 1, 1)
        self.cel_8_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_8_2.sizePolicy().hasHeightForWidth())
        self.cel_8_2.setSizePolicy(sizePolicy)
        self.cel_8_2.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_8_2.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_8_2.setFont(font)
        self.cel_8_2.setMaxLength(1)
        self.cel_8_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_8_2.setPlaceholderText(_fromUtf8(""))
        self.cel_8_2.setObjectName(_fromUtf8("cel_8_2"))
        self.gridLayout.addWidget(self.cel_8_2, 8, 2, 1, 1)
        self.cel_8_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_8_3.sizePolicy().hasHeightForWidth())
        self.cel_8_3.setSizePolicy(sizePolicy)
        self.cel_8_3.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_8_3.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_8_3.setFont(font)
        self.cel_8_3.setMaxLength(1)
        self.cel_8_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_8_3.setPlaceholderText(_fromUtf8(""))
        self.cel_8_3.setObjectName(_fromUtf8("cel_8_3"))
        self.gridLayout.addWidget(self.cel_8_3, 8, 3, 1, 1)
        self.cel_8_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_8_4.sizePolicy().hasHeightForWidth())
        self.cel_8_4.setSizePolicy(sizePolicy)
        self.cel_8_4.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_8_4.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_8_4.setFont(font)
        self.cel_8_4.setMaxLength(1)
        self.cel_8_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_8_4.setPlaceholderText(_fromUtf8(""))
        self.cel_8_4.setObjectName(_fromUtf8("cel_8_4"))
        self.gridLayout.addWidget(self.cel_8_4, 8, 4, 1, 1)
        self.cel_8_5 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_8_5.sizePolicy().hasHeightForWidth())
        self.cel_8_5.setSizePolicy(sizePolicy)
        self.cel_8_5.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_8_5.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_8_5.setFont(font)
        self.cel_8_5.setMaxLength(1)
        self.cel_8_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_8_5.setPlaceholderText(_fromUtf8(""))
        self.cel_8_5.setObjectName(_fromUtf8("cel_8_5"))
        self.gridLayout.addWidget(self.cel_8_5, 8, 5, 1, 1)
        self.cel_8_6 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_8_6.sizePolicy().hasHeightForWidth())
        self.cel_8_6.setSizePolicy(sizePolicy)
        self.cel_8_6.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_8_6.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_8_6.setFont(font)
        self.cel_8_6.setMaxLength(1)
        self.cel_8_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_8_6.setPlaceholderText(_fromUtf8(""))
        self.cel_8_6.setObjectName(_fromUtf8("cel_8_6"))
        self.gridLayout.addWidget(self.cel_8_6, 8, 6, 1, 1)
        self.cel_8_7 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_8_7.sizePolicy().hasHeightForWidth())
        self.cel_8_7.setSizePolicy(sizePolicy)
        self.cel_8_7.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_8_7.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_8_7.setFont(font)
        self.cel_8_7.setMaxLength(1)
        self.cel_8_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_8_7.setPlaceholderText(_fromUtf8(""))
        self.cel_8_7.setObjectName(_fromUtf8("cel_8_7"))
        self.gridLayout.addWidget(self.cel_8_7, 8, 7, 1, 1)
        self.cel_8_8 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cel_8_8.sizePolicy().hasHeightForWidth())
        self.cel_8_8.setSizePolicy(sizePolicy)
        self.cel_8_8.setMinimumSize(QtCore.QSize(45, 45))
        self.cel_8_8.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cel_8_8.setFont(font)
        self.cel_8_8.setMaxLength(1)
        self.cel_8_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_8_8.setPlaceholderText(_fromUtf8(""))
        self.cel_8_8.setObjectName(_fromUtf8("cel_8_8"))
        self.gridLayout.addWidget(self.cel_8_8, 8, 8, 1, 1)
        self.validateButton = QtGui.QPushButton(self.centralwidget)
        self.validateButton.setGeometry(QtCore.QRect(5, 560, 154, 27))
        self.validateButton.setObjectName(_fromUtf8("validateButton"))
        self.messages = QtGui.QLabel(self.centralwidget)
        self.messages.setGeometry(QtCore.QRect(10, 490, 462, 52))
        self.messages.setMinimumSize(QtCore.QSize(462, 52))
        self.messages.setMaximumSize(QtCore.QSize(462, 52))
        self.messages.setText(_fromUtf8(""))
        self.messages.setAlignment(QtCore.Qt.AlignCenter)
        self.messages.setWordWrap(True)
        self.messages.setObjectName(_fromUtf8("messages"))
        self.lineH1 = QtGui.QFrame(self.centralwidget)
        self.lineH1.setGeometry(QtCore.QRect(5, 165, 473, 3))
        self.lineH1.setFrameShadow(QtGui.QFrame.Plain)
        self.lineH1.setFrameShape(QtGui.QFrame.HLine)
        self.lineH1.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineH1.setObjectName(_fromUtf8("lineH1"))
        self.lineH2 = QtGui.QFrame(self.centralwidget)
        self.lineH2.setGeometry(QtCore.QRect(5, 321, 473, 3))
        self.lineH2.setFrameShadow(QtGui.QFrame.Plain)
        self.lineH2.setFrameShape(QtGui.QFrame.HLine)
        self.lineH2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineH2.setObjectName(_fromUtf8("lineH2"))
        self.lineV1 = QtGui.QFrame(self.centralwidget)
        self.lineV1.setGeometry(QtCore.QRect(162, 5, 3, 480))
        self.lineV1.setFrameShadow(QtGui.QFrame.Plain)
        self.lineV1.setFrameShape(QtGui.QFrame.VLine)
        self.lineV1.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineV1.setObjectName(_fromUtf8("lineV1"))
        self.lineV2 = QtGui.QFrame(self.centralwidget)
        self.lineV2.setGeometry(QtCore.QRect(315, 5, 3, 480))
        self.lineV2.setFrameShadow(QtGui.QFrame.Plain)
        self.lineV2.setFrameShape(QtGui.QFrame.VLine)
        self.lineV2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineV2.setObjectName(_fromUtf8("lineV2"))
        self.resetButton = QtGui.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(162, 560, 154, 27))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.newButton = QtGui.QPushButton(self.centralwidget)
        self.newButton.setGeometry(QtCore.QRect(320, 560, 154, 27))
        self.newButton.setObjectName(_fromUtf8("newButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 483, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cel_0_0, self.cel_0_1)
        MainWindow.setTabOrder(self.cel_0_1, self.cel_0_2)
        MainWindow.setTabOrder(self.cel_0_2, self.cel_0_3)
        MainWindow.setTabOrder(self.cel_0_3, self.cel_0_4)
        MainWindow.setTabOrder(self.cel_0_4, self.cel_0_5)
        MainWindow.setTabOrder(self.cel_0_5, self.cel_0_6)
        MainWindow.setTabOrder(self.cel_0_6, self.cel_0_7)
        MainWindow.setTabOrder(self.cel_0_7, self.cel_0_8)
        MainWindow.setTabOrder(self.cel_0_8, self.cel_1_0)
        MainWindow.setTabOrder(self.cel_1_0, self.cel_1_1)
        MainWindow.setTabOrder(self.cel_1_1, self.cel_1_2)
        MainWindow.setTabOrder(self.cel_1_2, self.cel_1_3)
        MainWindow.setTabOrder(self.cel_1_3, self.cel_1_4)
        MainWindow.setTabOrder(self.cel_1_4, self.cel_1_5)
        MainWindow.setTabOrder(self.cel_1_5, self.cel_1_6)
        MainWindow.setTabOrder(self.cel_1_6, self.cel_1_7)
        MainWindow.setTabOrder(self.cel_1_7, self.cel_1_8)
        MainWindow.setTabOrder(self.cel_1_8, self.cel_2_0)
        MainWindow.setTabOrder(self.cel_2_0, self.cel_2_1)
        MainWindow.setTabOrder(self.cel_2_1, self.cel_2_2)
        MainWindow.setTabOrder(self.cel_2_2, self.cel_2_3)
        MainWindow.setTabOrder(self.cel_2_3, self.cel_2_4)
        MainWindow.setTabOrder(self.cel_2_4, self.cel_2_5)
        MainWindow.setTabOrder(self.cel_2_5, self.cel_2_6)
        MainWindow.setTabOrder(self.cel_2_6, self.cel_2_7)
        MainWindow.setTabOrder(self.cel_2_7, self.cel_2_8)
        MainWindow.setTabOrder(self.cel_2_8, self.cel_3_0)
        MainWindow.setTabOrder(self.cel_3_0, self.cel_3_1)
        MainWindow.setTabOrder(self.cel_3_1, self.cel_3_2)
        MainWindow.setTabOrder(self.cel_3_2, self.cel_3_3)
        MainWindow.setTabOrder(self.cel_3_3, self.cel_3_4)
        MainWindow.setTabOrder(self.cel_3_4, self.cel_3_5)
        MainWindow.setTabOrder(self.cel_3_5, self.cel_3_6)
        MainWindow.setTabOrder(self.cel_3_6, self.cel_3_7)
        MainWindow.setTabOrder(self.cel_3_7, self.cel_3_8)
        MainWindow.setTabOrder(self.cel_3_8, self.cel_4_0)
        MainWindow.setTabOrder(self.cel_4_0, self.cel_4_1)
        MainWindow.setTabOrder(self.cel_4_1, self.cel_4_2)
        MainWindow.setTabOrder(self.cel_4_2, self.cel_4_3)
        MainWindow.setTabOrder(self.cel_4_3, self.cel_4_4)
        MainWindow.setTabOrder(self.cel_4_4, self.cel_4_5)
        MainWindow.setTabOrder(self.cel_4_5, self.cel_4_6)
        MainWindow.setTabOrder(self.cel_4_6, self.cel_4_7)
        MainWindow.setTabOrder(self.cel_4_7, self.cel_4_8)
        MainWindow.setTabOrder(self.cel_4_8, self.cel_5_0)
        MainWindow.setTabOrder(self.cel_5_0, self.cel_5_1)
        MainWindow.setTabOrder(self.cel_5_1, self.cel_5_2)
        MainWindow.setTabOrder(self.cel_5_2, self.cel_5_3)
        MainWindow.setTabOrder(self.cel_5_3, self.cel_5_4)
        MainWindow.setTabOrder(self.cel_5_4, self.cel_5_5)
        MainWindow.setTabOrder(self.cel_5_5, self.cel_5_6)
        MainWindow.setTabOrder(self.cel_5_6, self.cel_5_7)
        MainWindow.setTabOrder(self.cel_5_7, self.cel_5_8)
        MainWindow.setTabOrder(self.cel_5_8, self.cel_6_0)
        MainWindow.setTabOrder(self.cel_6_0, self.cel_6_1)
        MainWindow.setTabOrder(self.cel_6_1, self.cel_6_2)
        MainWindow.setTabOrder(self.cel_6_2, self.cel_6_3)
        MainWindow.setTabOrder(self.cel_6_3, self.cel_6_4)
        MainWindow.setTabOrder(self.cel_6_4, self.cel_6_5)
        MainWindow.setTabOrder(self.cel_6_5, self.cel_6_6)
        MainWindow.setTabOrder(self.cel_6_6, self.cel_6_7)
        MainWindow.setTabOrder(self.cel_6_7, self.cel_6_8)
        MainWindow.setTabOrder(self.cel_6_8, self.cel_7_0)
        MainWindow.setTabOrder(self.cel_7_0, self.cel_7_1)
        MainWindow.setTabOrder(self.cel_7_1, self.cel_7_2)
        MainWindow.setTabOrder(self.cel_7_2, self.cel_7_3)
        MainWindow.setTabOrder(self.cel_7_3, self.cel_7_4)
        MainWindow.setTabOrder(self.cel_7_4, self.cel_7_5)
        MainWindow.setTabOrder(self.cel_7_5, self.cel_7_6)
        MainWindow.setTabOrder(self.cel_7_6, self.cel_7_7)
        MainWindow.setTabOrder(self.cel_7_7, self.cel_7_8)
        MainWindow.setTabOrder(self.cel_7_8, self.cel_8_0)
        MainWindow.setTabOrder(self.cel_8_0, self.cel_8_1)
        MainWindow.setTabOrder(self.cel_8_1, self.cel_8_2)
        MainWindow.setTabOrder(self.cel_8_2, self.cel_8_3)
        MainWindow.setTabOrder(self.cel_8_3, self.cel_8_4)
        MainWindow.setTabOrder(self.cel_8_4, self.cel_8_5)
        MainWindow.setTabOrder(self.cel_8_5, self.cel_8_6)
        MainWindow.setTabOrder(self.cel_8_6, self.cel_8_7)
        MainWindow.setTabOrder(self.cel_8_7, self.cel_8_8)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "The Sudoku", None))
        self.validateButton.setText(_translate("MainWindow", "Validar", None))
        self.resetButton.setText(_translate("MainWindow", "Reset", None))
        self.newButton.setText(_translate("MainWindow", "Nou joc", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

