# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'palanca.ui'
#
# Created: Wed Feb 17 20:12:36 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(676, 498)
        MainWindow.setMinimumSize(QtCore.QSize(676, 498))
        MainWindow.setMaximumSize(QtCore.QSize(676, 498))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.brmenys = QtGui.QPushButton(self.centralwidget)
        self.brmenys.setGeometry(QtCore.QRect(50, 270, 90, 27))
        self.brmenys.setObjectName(_fromUtf8("brmenys"))
        self.brmes = QtGui.QPushButton(self.centralwidget)
        self.brmes.setGeometry(QtCore.QRect(230, 270, 90, 27))
        self.brmes.setObjectName(_fromUtf8("brmes"))
        self.bpmenys = QtGui.QPushButton(self.centralwidget)
        self.bpmenys.setGeometry(QtCore.QRect(370, 270, 90, 27))
        self.bpmenys.setObjectName(_fromUtf8("bpmenys"))
        self.bpmes = QtGui.QPushButton(self.centralwidget)
        self.bpmes.setGeometry(QtCore.QRect(550, 270, 90, 27))
        self.bpmes.setObjectName(_fromUtf8("bpmes"))
        self.sliderBR = QtGui.QSlider(self.centralwidget)
        self.sliderBR.setGeometry(QtCore.QRect(49, 350, 271, 29))
        self.sliderBR.setMaximum(999)
        self.sliderBR.setPageStep(1)
        self.sliderBR.setProperty("value", 500)
        self.sliderBR.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBR.setObjectName(_fromUtf8("sliderBR"))
        self.sliderBP = QtGui.QSlider(self.centralwidget)
        self.sliderBP.setGeometry(QtCore.QRect(370, 350, 271, 29))
        self.sliderBP.setMaximum(999)
        self.sliderBP.setPageStep(1)
        self.sliderBP.setProperty("value", 500)
        self.sliderBP.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBP.setObjectName(_fromUtf8("sliderBP"))
        self.capcelera = QtGui.QLabel(self.centralwidget)
        self.capcelera.setGeometry(QtCore.QRect(90, 0, 591, 90))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.capcelera.setFont(font)
        self.capcelera.setStyleSheet(_fromUtf8("background-color: rgb(167, 167, 167);\n"
"color: white;"))
        self.capcelera.setScaledContents(False)
        self.capcelera.setAlignment(QtCore.Qt.AlignCenter)
        self.capcelera.setWordWrap(False)
        self.capcelera.setObjectName(_fromUtf8("capcelera"))
        self.palanca = QtGui.QLabel(self.centralwidget)
        self.palanca.setGeometry(QtCore.QRect(370, 100, 271, 91))
        self.palanca.setMinimumSize(QtCore.QSize(271, 91))
        self.palanca.setMaximumSize(QtCore.QSize(271, 91))
        self.palanca.setStyleSheet(_fromUtf8("background-image: url(\"palanca.jpg\");"))
        self.palanca.setText(_fromUtf8(""))
        self.palanca.setPixmap(QtGui.QPixmap(_fromUtf8("imatges_palanca/palanca.jpg")))
        self.palanca.setScaledContents(True)
        self.palanca.setAlignment(QtCore.Qt.AlignCenter)
        self.palanca.setObjectName(_fromUtf8("palanca"))
        self.resultat = QtGui.QLabel(self.centralwidget)
        self.resultat.setGeometry(QtCore.QRect(50, 110, 271, 91))
        self.resultat.setMinimumSize(QtCore.QSize(271, 91))
        self.resultat.setMaximumSize(QtCore.QSize(271, 91))
        self.resultat.setText(_fromUtf8(""))
        self.resultat.setScaledContents(True)
        self.resultat.setAlignment(QtCore.Qt.AlignCenter)
        self.resultat.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.resultat.setObjectName(_fromUtf8("resultat"))
        self.lcdBR = QtGui.QLCDNumber(self.centralwidget)
        self.lcdBR.setGeometry(QtCore.QRect(150, 400, 80, 50))
        self.lcdBR.setMinimumSize(QtCore.QSize(80, 50))
        self.lcdBR.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdBR.setFont(font)
        self.lcdBR.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.lcdBR.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdBR.setNumDigits(3)
        self.lcdBR.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdBR.setProperty("value", 500.0)
        self.lcdBR.setObjectName(_fromUtf8("lcdBR"))
        self.lcdBP = QtGui.QLCDNumber(self.centralwidget)
        self.lcdBP.setGeometry(QtCore.QRect(470, 400, 80, 50))
        self.lcdBP.setMinimumSize(QtCore.QSize(80, 50))
        self.lcdBP.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdBP.setFont(font)
        self.lcdBP.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdBP.setNumDigits(3)
        self.lcdBP.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdBP.setProperty("value", 500.0)
        self.lcdBP.setObjectName(_fromUtf8("lcdBP"))
        self.R = QtGui.QLabel(self.centralwidget)
        self.R.setGeometry(QtCore.QRect(150, 260, 60, 51))
        self.R.setMinimumSize(QtCore.QSize(60, 51))
        self.R.setMaximumSize(QtCore.QSize(60, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.R.setFont(font)
        self.R.setMidLineWidth(0)
        self.R.setAlignment(QtCore.Qt.AlignCenter)
        self.R.setObjectName(_fromUtf8("R"))
        self.P = QtGui.QLabel(self.centralwidget)
        self.P.setGeometry(QtCore.QRect(470, 260, 60, 51))
        self.P.setMinimumSize(QtCore.QSize(60, 51))
        self.P.setMaximumSize(QtCore.QSize(60, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.P.setFont(font)
        self.P.setAlignment(QtCore.Qt.AlignCenter)
        self.P.setObjectName(_fromUtf8("P"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 90, 90))
        self.label.setMinimumSize(QtCore.QSize(90, 90))
        self.label.setMaximumSize(QtCore.QSize(90, 90))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("imatges_palanca/arquimedes_palanca_mundo.jpg")))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 230, 60, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 230, 60, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 320, 60, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 320, 60, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.sliderBR, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdBR.display)
        QtCore.QObject.connect(self.sliderBP, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdBP.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Ley de la palanca", None))
        self.brmenys.setText(_translate("MainWindow", "-", None))
        self.brmes.setText(_translate("MainWindow", "+", None))
        self.bpmenys.setText(_translate("MainWindow", "-", None))
        self.bpmes.setText(_translate("MainWindow", "+", None))
        self.capcelera.setText(_translate("MainWindow", "Ley de la palanca - Arquímedes", None))
        self.R.setText(_translate("MainWindow", "500", None))
        self.P.setText(_translate("MainWindow", "500", None))
        self.label_2.setText(_translate("MainWindow", "R", None))
        self.label_3.setText(_translate("MainWindow", "P", None))
        self.label_4.setText(_translate("MainWindow", "BR", None))
        self.label_5.setText(_translate("MainWindow", "BP", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

