# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sudoku.ui'
#
# Created: Tue Dec  8 14:12:16 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(255, 340)
        MainWindow.setMinimumSize(QtCore.QSize(255, 340))
        MainWindow.setMaximumSize(QtCore.QSize(422, 340))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(422, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(422, 16777215))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 231, 221))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cel_2_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_2_0.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_2_0.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_2_0.setFont(font)
        self.cel_2_0.setMaxLength(1)
        self.cel_2_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_0.setObjectName(_fromUtf8("cel_2_0"))
        self.gridLayout.addWidget(self.cel_2_0, 2, 0, 1, 1)
        self.cel_2_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_2_1.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_2_1.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_2_1.setFont(font)
        self.cel_2_1.setMaxLength(1)
        self.cel_2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_1.setObjectName(_fromUtf8("cel_2_1"))
        self.gridLayout.addWidget(self.cel_2_1, 2, 1, 1, 1)
        self.cel_0_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_0_1.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_0_1.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_0_1.setFont(font)
        self.cel_0_1.setMaxLength(1)
        self.cel_0_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_1.setObjectName(_fromUtf8("cel_0_1"))
        self.gridLayout.addWidget(self.cel_0_1, 0, 1, 1, 1)
        self.cel_2_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_2_3.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_2_3.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_2_3.setFont(font)
        self.cel_2_3.setMaxLength(1)
        self.cel_2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_3.setObjectName(_fromUtf8("cel_2_3"))
        self.gridLayout.addWidget(self.cel_2_3, 2, 3, 1, 1)
        self.cel_0_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_0_3.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_0_3.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_0_3.setFont(font)
        self.cel_0_3.setMaxLength(1)
        self.cel_0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_3.setObjectName(_fromUtf8("cel_0_3"))
        self.gridLayout.addWidget(self.cel_0_3, 0, 3, 1, 1)
        self.cel_1_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_1_1.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_1_1.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_1_1.setFont(font)
        self.cel_1_1.setMaxLength(1)
        self.cel_1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_1.setObjectName(_fromUtf8("cel_1_1"))
        self.gridLayout.addWidget(self.cel_1_1, 1, 1, 1, 1)
        self.cel_0_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_0_0.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_0_0.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_0_0.setFont(font)
        self.cel_0_0.setMaxLength(1)
        self.cel_0_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_0.setObjectName(_fromUtf8("cel_0_0"))
        self.gridLayout.addWidget(self.cel_0_0, 0, 0, 1, 1)
        self.cel_2_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_2_2.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_2_2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_2_2.setFont(font)
        self.cel_2_2.setMaxLength(1)
        self.cel_2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_2.setObjectName(_fromUtf8("cel_2_2"))
        self.gridLayout.addWidget(self.cel_2_2, 2, 2, 1, 1)
        self.cel_0_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_0_2.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_0_2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_0_2.setFont(font)
        self.cel_0_2.setMaxLength(1)
        self.cel_0_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_2.setObjectName(_fromUtf8("cel_0_2"))
        self.gridLayout.addWidget(self.cel_0_2, 0, 2, 1, 1)
        self.cel_1_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_1_0.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_1_0.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_1_0.setFont(font)
        self.cel_1_0.setMaxLength(1)
        self.cel_1_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_0.setObjectName(_fromUtf8("cel_1_0"))
        self.gridLayout.addWidget(self.cel_1_0, 1, 0, 1, 1)
        self.cel_1_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_1_2.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_1_2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_1_2.setFont(font)
        self.cel_1_2.setMaxLength(1)
        self.cel_1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_2.setObjectName(_fromUtf8("cel_1_2"))
        self.gridLayout.addWidget(self.cel_1_2, 1, 2, 1, 1)
        self.cel_1_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_1_3.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_1_3.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_1_3.setFont(font)
        self.cel_1_3.setMaxLength(1)
        self.cel_1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_3.setObjectName(_fromUtf8("cel_1_3"))
        self.gridLayout.addWidget(self.cel_1_3, 1, 3, 1, 1)
        self.cel_3_1 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_3_1.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_3_1.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_3_1.setFont(font)
        self.cel_3_1.setMaxLength(1)
        self.cel_3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_1.setObjectName(_fromUtf8("cel_3_1"))
        self.gridLayout.addWidget(self.cel_3_1, 3, 1, 1, 1)
        self.cel_3_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_3_2.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_3_2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_3_2.setFont(font)
        self.cel_3_2.setMaxLength(1)
        self.cel_3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_2.setObjectName(_fromUtf8("cel_3_2"))
        self.gridLayout.addWidget(self.cel_3_2, 3, 2, 1, 1)
        self.cel_3_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_3_3.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_3_3.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_3_3.setFont(font)
        self.cel_3_3.setMaxLength(1)
        self.cel_3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_3.setObjectName(_fromUtf8("cel_3_3"))
        self.gridLayout.addWidget(self.cel_3_3, 3, 3, 1, 1)
        self.cel_3_0 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.cel_3_0.setMinimumSize(QtCore.QSize(50, 50))
        self.cel_3_0.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cel_3_0.setFont(font)
        self.cel_3_0.setMaxLength(1)
        self.cel_3_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_0.setObjectName(_fromUtf8("cel_3_0"))
        self.gridLayout.addWidget(self.cel_3_0, 3, 0, 1, 1)
        self.lineH = QtGui.QFrame(self.centralwidget)
        self.lineH.setGeometry(QtCore.QRect(4, 113, 245, 10))
        self.lineH.setMinimumSize(QtCore.QSize(245, 10))
        self.lineH.setMaximumSize(QtCore.QSize(245, 10))
        self.lineH.setFrameShadow(QtGui.QFrame.Plain)
        self.lineH.setLineWidth(2)
        self.lineH.setFrameShape(QtGui.QFrame.HLine)
        self.lineH.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineH.setObjectName(_fromUtf8("lineH"))
        self.lineV = QtGui.QFrame(self.centralwidget)
        self.lineV.setGeometry(QtCore.QRect(119, 5, 10, 230))
        self.lineV.setMinimumSize(QtCore.QSize(10, 230))
        self.lineV.setMaximumSize(QtCore.QSize(10, 230))
        self.lineV.setFrameShadow(QtGui.QFrame.Plain)
        self.lineV.setLineWidth(2)
        self.lineV.setFrameShape(QtGui.QFrame.VLine)
        self.lineV.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineV.setObjectName(_fromUtf8("lineV"))
        self.messages = QtGui.QLabel(self.centralwidget)
        self.messages.setGeometry(QtCore.QRect(10, 240, 235, 30))
        self.messages.setMinimumSize(QtCore.QSize(235, 30))
        self.messages.setMaximumSize(QtCore.QSize(235, 30))
        self.messages.setBaseSize(QtCore.QSize(0, 0))
        self.messages.setText(_fromUtf8(""))
        self.messages.setAlignment(QtCore.Qt.AlignCenter)
        self.messages.setWordWrap(True)
        self.messages.setObjectName(_fromUtf8("messages"))
        self.validateButton = QtGui.QPushButton(self.centralwidget)
        self.validateButton.setGeometry(QtCore.QRect(10, 280, 115, 28))
        self.validateButton.setMinimumSize(QtCore.QSize(115, 28))
        self.validateButton.setMaximumSize(QtCore.QSize(115, 28))
        self.validateButton.setObjectName(_fromUtf8("validateButton"))
        self.resetButton = QtGui.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(128, 280, 115, 28))
        self.resetButton.setMinimumSize(QtCore.QSize(115, 28))
        self.resetButton.setMaximumSize(QtCore.QSize(115, 28))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cel_0_0, self.cel_0_1)
        MainWindow.setTabOrder(self.cel_0_1, self.cel_0_2)
        MainWindow.setTabOrder(self.cel_0_2, self.cel_0_3)
        MainWindow.setTabOrder(self.cel_0_3, self.cel_1_0)
        MainWindow.setTabOrder(self.cel_1_0, self.cel_1_1)
        MainWindow.setTabOrder(self.cel_1_1, self.cel_1_2)
        MainWindow.setTabOrder(self.cel_1_2, self.cel_1_3)
        MainWindow.setTabOrder(self.cel_1_3, self.cel_2_0)
        MainWindow.setTabOrder(self.cel_2_0, self.cel_2_1)
        MainWindow.setTabOrder(self.cel_2_1, self.cel_2_2)
        MainWindow.setTabOrder(self.cel_2_2, self.cel_2_3)
        MainWindow.setTabOrder(self.cel_2_3, self.cel_3_0)
        MainWindow.setTabOrder(self.cel_3_0, self.cel_3_1)
        MainWindow.setTabOrder(self.cel_3_1, self.cel_3_2)
        MainWindow.setTabOrder(self.cel_3_2, self.cel_3_3)
        MainWindow.setTabOrder(self.cel_3_3, self.validateButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "The Sudoku", None))
        self.validateButton.setText(_translate("MainWindow", "Validar", None))
        self.resetButton.setText(_translate("MainWindow", "Reset", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

