# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quadrat_magic.ui'
#
# Created: Sun Jan  3 15:27:09 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(445, 567)
        MainWindow.setMinimumSize(QtCore.QSize(445, 567))
        MainWindow.setMaximumSize(QtCore.QSize(445, 567))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.titol = QtGui.QLabel(self.centralwidget)
        self.titol.setGeometry(QtCore.QRect(20, 20, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.titol.setFont(font)
        self.titol.setStyleSheet(_fromUtf8("color:blue;"))
        self.titol.setAlignment(QtCore.Qt.AlignCenter)
        self.titol.setObjectName(_fromUtf8("titol"))
        self.calcula = QtGui.QPushButton(self.centralwidget)
        self.calcula.setGeometry(QtCore.QRect(20, 435, 190, 28))
        self.calcula.setMinimumSize(QtCore.QSize(190, 28))
        self.calcula.setMaximumSize(QtCore.QSize(190, 28))
        self.calcula.setObjectName(_fromUtf8("calcula"))
        self.missatges = QtGui.QLabel(self.centralwidget)
        self.missatges.setGeometry(QtCore.QRect(20, 480, 400, 50))
        self.missatges.setMinimumSize(QtCore.QSize(400, 50))
        self.missatges.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.missatges.setFont(font)
        self.missatges.setStyleSheet(_fromUtf8(""))
        self.missatges.setText(_fromUtf8(""))
        self.missatges.setAlignment(QtCore.Qt.AlignCenter)
        self.missatges.setWordWrap(True)
        self.missatges.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.missatges.setObjectName(_fromUtf8("missatges"))
        self.reset = QtGui.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(230, 435, 190, 28))
        self.reset.setMinimumSize(QtCore.QSize(190, 28))
        self.reset.setMaximumSize(QtCore.QSize(190, 28))
        self.reset.setObjectName(_fromUtf8("reset"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 100, 401, 320))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cel_0_0 = QtGui.QLineEdit(self.layoutWidget)
        self.cel_0_0.setMinimumSize(QtCore.QSize(75, 75))
        self.cel_0_0.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_0_0.setFont(font)
        self.cel_0_0.setMaxLength(1)
        self.cel_0_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_0.setObjectName(_fromUtf8("cel_0_0"))
        self.gridLayout.addWidget(self.cel_0_0, 0, 1, 1, 1)
        self.cel_0_1 = QtGui.QLineEdit(self.layoutWidget)
        self.cel_0_1.setMinimumSize(QtCore.QSize(75, 75))
        self.cel_0_1.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_0_1.setFont(font)
        self.cel_0_1.setMaxLength(1)
        self.cel_0_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_1.setObjectName(_fromUtf8("cel_0_1"))
        self.gridLayout.addWidget(self.cel_0_1, 0, 2, 1, 1)
        self.cel_0_2 = QtGui.QLineEdit(self.layoutWidget)
        self.cel_0_2.setMinimumSize(QtCore.QSize(75, 75))
        self.cel_0_2.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_0_2.setFont(font)
        self.cel_0_2.setMaxLength(1)
        self.cel_0_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_2.setObjectName(_fromUtf8("cel_0_2"))
        self.gridLayout.addWidget(self.cel_0_2, 0, 3, 1, 1)
        self.cel_0_3 = QtGui.QLabel(self.layoutWidget)
        self.cel_0_3.setMinimumSize(QtCore.QSize(73, 73))
        self.cel_0_3.setMaximumSize(QtCore.QSize(73, 73))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_0_3.setFont(font)
        self.cel_0_3.setStyleSheet(_fromUtf8("background-color: rgb(236,236,236);\n"
"border: 1px solid rgb(204,204,204);\n"
"border-radius: 3px;"))
        self.cel_0_3.setText(_fromUtf8(""))
        self.cel_0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_0_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.cel_0_3.setObjectName(_fromUtf8("cel_0_3"))
        self.gridLayout.addWidget(self.cel_0_3, 0, 4, 1, 1)
        self.cel_1_0 = QtGui.QLineEdit(self.layoutWidget)
        self.cel_1_0.setMinimumSize(QtCore.QSize(75, 75))
        self.cel_1_0.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_1_0.setFont(font)
        self.cel_1_0.setMaxLength(1)
        self.cel_1_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_0.setObjectName(_fromUtf8("cel_1_0"))
        self.gridLayout.addWidget(self.cel_1_0, 1, 1, 1, 1)
        self.cel_1_1 = QtGui.QLineEdit(self.layoutWidget)
        self.cel_1_1.setMinimumSize(QtCore.QSize(75, 75))
        self.cel_1_1.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_1_1.setFont(font)
        self.cel_1_1.setMaxLength(1)
        self.cel_1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_1.setObjectName(_fromUtf8("cel_1_1"))
        self.gridLayout.addWidget(self.cel_1_1, 1, 2, 1, 1)
        self.cel_1_2 = QtGui.QLineEdit(self.layoutWidget)
        self.cel_1_2.setMinimumSize(QtCore.QSize(75, 75))
        self.cel_1_2.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_1_2.setFont(font)
        self.cel_1_2.setMaxLength(1)
        self.cel_1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_2.setObjectName(_fromUtf8("cel_1_2"))
        self.gridLayout.addWidget(self.cel_1_2, 1, 3, 1, 1)
        self.cel_1_3 = QtGui.QLabel(self.layoutWidget)
        self.cel_1_3.setMinimumSize(QtCore.QSize(73, 73))
        self.cel_1_3.setMaximumSize(QtCore.QSize(73, 73))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_1_3.setFont(font)
        self.cel_1_3.setStyleSheet(_fromUtf8("background-color: rgb(236,236,236);\n"
"border: 1px solid rgb(204,204,204);\n"
"border-radius: 3px;"))
        self.cel_1_3.setText(_fromUtf8(""))
        self.cel_1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_1_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.cel_1_3.setObjectName(_fromUtf8("cel_1_3"))
        self.gridLayout.addWidget(self.cel_1_3, 1, 4, 1, 1)
        self.cel_2_0 = QtGui.QLineEdit(self.layoutWidget)
        self.cel_2_0.setMinimumSize(QtCore.QSize(75, 75))
        self.cel_2_0.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_2_0.setFont(font)
        self.cel_2_0.setMaxLength(1)
        self.cel_2_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_0.setObjectName(_fromUtf8("cel_2_0"))
        self.gridLayout.addWidget(self.cel_2_0, 2, 1, 1, 1)
        self.cel_2_1 = QtGui.QLineEdit(self.layoutWidget)
        self.cel_2_1.setMinimumSize(QtCore.QSize(75, 75))
        self.cel_2_1.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_2_1.setFont(font)
        self.cel_2_1.setMaxLength(1)
        self.cel_2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_1.setObjectName(_fromUtf8("cel_2_1"))
        self.gridLayout.addWidget(self.cel_2_1, 2, 2, 1, 1)
        self.cel_2_2 = QtGui.QLineEdit(self.layoutWidget)
        self.cel_2_2.setMinimumSize(QtCore.QSize(75, 75))
        self.cel_2_2.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_2_2.setFont(font)
        self.cel_2_2.setMaxLength(1)
        self.cel_2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_2.setObjectName(_fromUtf8("cel_2_2"))
        self.gridLayout.addWidget(self.cel_2_2, 2, 3, 1, 1)
        self.cel_2_3 = QtGui.QLabel(self.layoutWidget)
        self.cel_2_3.setMinimumSize(QtCore.QSize(73, 73))
        self.cel_2_3.setMaximumSize(QtCore.QSize(73, 73))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_2_3.setFont(font)
        self.cel_2_3.setStyleSheet(_fromUtf8("background-color: rgb(236,236,236);\n"
"border: 1px solid rgb(204,204,204);\n"
"border-radius: 3px;"))
        self.cel_2_3.setText(_fromUtf8(""))
        self.cel_2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_2_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.cel_2_3.setObjectName(_fromUtf8("cel_2_3"))
        self.gridLayout.addWidget(self.cel_2_3, 2, 4, 1, 1)
        self.D2 = QtGui.QLabel(self.layoutWidget)
        self.D2.setMinimumSize(QtCore.QSize(73, 73))
        self.D2.setMaximumSize(QtCore.QSize(73, 73))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.D2.setFont(font)
        self.D2.setStyleSheet(_fromUtf8("background-color: rgb(236,236,236);\n"
"border: 1px solid rgb(204,204,204);\n"
"border-radius: 3px;"))
        self.D2.setText(_fromUtf8(""))
        self.D2.setAlignment(QtCore.Qt.AlignCenter)
        self.D2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.D2.setObjectName(_fromUtf8("D2"))
        self.gridLayout.addWidget(self.D2, 3, 0, 1, 1)
        self.cel_3_0 = QtGui.QLabel(self.layoutWidget)
        self.cel_3_0.setMinimumSize(QtCore.QSize(73, 73))
        self.cel_3_0.setMaximumSize(QtCore.QSize(73, 73))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_3_0.setFont(font)
        self.cel_3_0.setStyleSheet(_fromUtf8("background-color: rgb(236,236,236);\n"
"border: 1px solid rgb(204,204,204);\n"
"border-radius: 3px;"))
        self.cel_3_0.setText(_fromUtf8(""))
        self.cel_3_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_0.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.cel_3_0.setObjectName(_fromUtf8("cel_3_0"))
        self.gridLayout.addWidget(self.cel_3_0, 3, 1, 1, 1)
        self.cel_3_1 = QtGui.QLabel(self.layoutWidget)
        self.cel_3_1.setMinimumSize(QtCore.QSize(73, 73))
        self.cel_3_1.setMaximumSize(QtCore.QSize(73, 73))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_3_1.setFont(font)
        self.cel_3_1.setStyleSheet(_fromUtf8("background-color: rgb(236,236,236);\n"
"border: 1px solid rgb(204,204,204);\n"
"border-radius: 3px;"))
        self.cel_3_1.setText(_fromUtf8(""))
        self.cel_3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.cel_3_1.setObjectName(_fromUtf8("cel_3_1"))
        self.gridLayout.addWidget(self.cel_3_1, 3, 2, 1, 1)
        self.cel_3_2 = QtGui.QLabel(self.layoutWidget)
        self.cel_3_2.setMinimumSize(QtCore.QSize(73, 73))
        self.cel_3_2.setMaximumSize(QtCore.QSize(73, 73))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cel_3_2.setFont(font)
        self.cel_3_2.setStyleSheet(_fromUtf8("background-color: rgb(236,236,236);\n"
"border: 1px solid rgb(204,204,204);\n"
"border-radius: 3px;"))
        self.cel_3_2.setText(_fromUtf8(""))
        self.cel_3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cel_3_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.cel_3_2.setObjectName(_fromUtf8("cel_3_2"))
        self.gridLayout.addWidget(self.cel_3_2, 3, 3, 1, 1)
        self.D1 = QtGui.QLabel(self.layoutWidget)
        self.D1.setMinimumSize(QtCore.QSize(73, 73))
        self.D1.setMaximumSize(QtCore.QSize(73, 73))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.D1.setFont(font)
        self.D1.setStyleSheet(_fromUtf8("background-color: rgb(236,236,236);\n"
"border: 1px solid rgb(204,204,204);\n"
"border-radius: 3px;"))
        self.D1.setText(_fromUtf8(""))
        self.D1.setAlignment(QtCore.Qt.AlignCenter)
        self.D1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.D1.setObjectName(_fromUtf8("D1"))
        self.gridLayout.addWidget(self.D1, 3, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cel_0_0, self.cel_0_1)
        MainWindow.setTabOrder(self.cel_0_1, self.cel_0_2)
        MainWindow.setTabOrder(self.cel_0_2, self.cel_1_0)
        MainWindow.setTabOrder(self.cel_1_0, self.cel_1_1)
        MainWindow.setTabOrder(self.cel_1_1, self.cel_1_2)
        MainWindow.setTabOrder(self.cel_1_2, self.cel_2_0)
        MainWindow.setTabOrder(self.cel_2_0, self.cel_2_1)
        MainWindow.setTabOrder(self.cel_2_1, self.cel_2_2)
        MainWindow.setTabOrder(self.cel_2_2, self.calcula)
        MainWindow.setTabOrder(self.calcula, self.reset)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Quadrat màgic", None))
        self.titol.setText(_translate("MainWindow", "Quadrat màgic 3X3", None))
        self.calcula.setText(_translate("MainWindow", "Calcula", None))
        self.reset.setText(_translate("MainWindow", "Reset", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

